// ============================================
// Barrel Exports - Todos os tipos
// ============================================

// Common
export type {
  UUID,
  BI,
  Email,
  Phone,
  ISODate,
  Timestamp,
  Percentage,
  PaginationParams,
  PaginatedResponse,
  SortOrder,
  SortParams,
  FilterParams,
  QueryParams,
  ApiSuccessResponse,
  ApiErrorResponse,
  ApiResponse,
  LoadingState,
  AsyncState,
  Address,
  PersonBase,
  IdentifiableEntity,
} from './common'

// Domain
export type {
  PacienteStatus,
  Paciente,
  PacienteCreate,
  PacienteLogin,
  PacienteResumo,
  TurnoTrabalho,
  Medico,
  MedicoCreate,
  EscalaMedico,
  ConsultaStatus,
  Consulta,
  ConsultaCreate,
  ConsultaResponse,
  SlotDisponivel,
  SlotsResponse,
  Falta,
  Feriado,
  AdminFuncao,
  Admin,
  AdminLogin,
  AdminSession,
  Configuracao,
  AuditLog,
  EmailStatus,
  EmailLog,
  MetricasPublicas,
  RelatorioPeriodo,
} from './domain'

// API
export type {
  GetSlotsResponse,
  GetSlotsParams,
  CreateAppointmentRequest,
  CreateAppointmentResponse,
  CancelAppointmentRequest,
  CancelAppointmentResponse,
  PatientLoginRequest,
  PatientLoginResponse,
  GetPatientConsultasParams,
  PatientConsultasResponse,
  AdminLoginRequest,
  AdminLoginResponse,
  GetAdminAppointmentsParams,
  GetAdminAppointmentsResponse,
  UpdateAppointmentStatusRequest,
  CreateDoctorRequest,
  GetDoctorsResponse,
  CreateDoctorResponse,
  GetReportsParams,
  GetReportsResponse,
  UpdateConfigRequest,
  ConfigResponse,
  CreateHolidayRequest,
  GetMetricsResponse,
} from './api'

// Form
export type {
  BookingFormData,
  BookingFormErrors,
  PatientLoginFormData,
  PatientLoginFormErrors,
  CancelFormData,
  AdminLoginFormData,
  AdminLoginFormErrors,
  DoctorFormData,
  DoctorFormErrors,
  HolidayFormData,
  HolidayFormErrors,
  FormState,
  FormAction,
} from './form'

// UI
export type {
  ButtonVariant,
  ButtonSize,
  BadgeVariant,
  InputType,
  ModalSize,
  SkeletonVariant,
  SelectOption,
  TabOption,
  StepConfig,
  TableColumn,
  MenuItem,
  BreadcrumbItem,
  ToastType,
  ToastConfig,
  CardPadding,
  ModalConfig,
  UIState,
} from './ui'